# Generated by Django 3.0.6 on 2020-06-17 19:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200116_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, blank=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
