# Generated by Django 3.0.8 on 2020-08-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_auto_20200317_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='url',
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refused', 'Refused'), ('approved', 'Approved')], default='pending', max_length=40),
        ),
    ]
