# Generated by Django 3.0.8 on 2020-07-05 08:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import funkwhale_api.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_actor_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', funkwhale_api.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, blank=True, max_length=50000),
        ),
    ]
