# Generated by Django 3.0.8 on 2020-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200718_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
