# Generated by Django 3.0.8 on 2020-08-03 12:22

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0004_auto_20180107_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
